version: '3.8'

services:
  api:
    build: ./backend
    env_file: ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  web:
    build: ./frontend
    env_file: ./frontend/.env
    ports:
      - "8080:80"

  mongo:                     # ← add this section
    image: mongo:6
    restart: always
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
